Restore `build`.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,52 +1,52 @@
 #!/bin/bash
 
-### Exit immediately on error.
-#set -e
-#
-## Echo to console.
-#set -x
-#
-#cleanup_test_containers() {
-#  CONTAINERS=$(docker ps -a -q --filter "name=sia-test-container")
-#  if [ ! -z $CONTAINERS ]; then
-#    docker stop $CONTAINERS
-#    docker rm   $CONTAINERS
-#  fi
-#}
-#
-#cleanup_test_containers
-#
-#for DIR in . ./alpine ./pi ./dev ./dev-debian ./debug
-#do
-#  docker build \
-#    --tag sia-image \
-#    -f $DIR/Dockerfile \
-#    .
-#
-#  export DUMMY_DATA_DIR=$(mktemp -d)
-#
-#  # Run container in detached state
-#  docker run \
-#    --detach \
-#    --publish 127.0.0.1:9988:9980 \
-#    --volume "${DUMMY_DATA_DIR}:/sia-data" \
-#    --env SIA_MODULES=cg \
-#    --name sia-test-container \
-#    sia-image
-#
-#  sleep 5s
-#
-#  if [ -e "${DUMMY_DATA_DIR}/consensus" ]; then
-#    (echo "Created consensus folder successfully" && exit 0)
-#  else
-#    (echo "Couldn't find consensus folder for image at $DIR" && \
-#      docker logs sia-test-container && \
-#      exit 1)
-#  fi
-#
-#  curl -A "Sia-Agent" "http://localhost:9988/consensus"
-#
-#  docker rm -f sia-test-container
-#done
-#
-#cleanup_test_containers
+## Exit immediately on error.
+set -e
+
+# Echo to console.
+set -x
+
+cleanup_test_containers() {
+  CONTAINERS=$(docker ps -a -q --filter "name=sia-test-container")
+  if [ ! -z $CONTAINERS ]; then
+    docker stop $CONTAINERS
+    docker rm   $CONTAINERS
+  fi
+}
+
+cleanup_test_containers
+
+for DIR in . ./alpine ./pi ./dev ./dev-debian ./debug
+do
+  docker build \
+    --tag sia-image \
+    -f $DIR/Dockerfile \
+    .
+
+  export DUMMY_DATA_DIR=$(mktemp -d)
+
+  # Run container in detached state
+  docker run \
+    --detach \
+    --publish 127.0.0.1:9988:9980 \
+    --volume "${DUMMY_DATA_DIR}:/sia-data" \
+    --env SIA_MODULES=cg \
+    --name sia-test-container \
+    sia-image
+
+  sleep 5s
+
+  if [ -e "${DUMMY_DATA_DIR}/consensus" ]; then
+    (echo "Created consensus folder successfully" && exit 0)
+  else
+    (echo "Couldn't find consensus folder for image at $DIR" && \
+      docker logs sia-test-container && \
+      exit 1)
+  fi
+
+  curl -A "Sia-Agent" "http://localhost:9988/consensus"
+
+  docker rm -f sia-test-container
+done
+
+cleanup_test_containers
