Adding a build test for the dev Dockerfile (#19)
* Adding a build test for the dev Dockerfile

* Adding better debugging on test failure

diff --git a/build b/build
--- a/build
+++ b/build
@@ -6,29 +6,36 @@ set -e
 # Echo to console.
 set -x
 
-docker build \
-  --tag sia-image \
-  .
+for DIR in ./ ./dev
+do
+  pushd $DIR
+  docker build \
+    --tag sia-image \
+    .
 
-export DUMMY_DATA_DIR=$(mktemp -d)
+  export DUMMY_DATA_DIR=$(mktemp -d)
 
-# Run container in detached state
-docker run \
-  --detach \
-  --publish 127.0.0.1:9980:9980 \
-  --volume "${DUMMY_DATA_DIR}:/sia-data" \
-  --env SIA_MODULES=cg \
-  --name sia-container \
-  sia-image
+  # Run container in detached state
+  docker run \
+    --detach \
+    --publish 127.0.0.1:9980:9980 \
+    --volume "${DUMMY_DATA_DIR}:/sia-data" \
+    --env SIA_MODULES=cg \
+    --name sia-container \
+    sia-image
 
-sleep 5s
+  sleep 5s
 
-if [ -e "${DUMMY_DATA_DIR}/consensus" ]; then
-  (echo "Created consensus folder successfully" && exit 0)
-else
-  (echo "Couldn't find consensus folder" && exit 1)
-fi
+  if [ -e "${DUMMY_DATA_DIR}/consensus" ]; then
+    (echo "Created consensus folder successfully" && exit 0)
+  else
+    (echo "Couldn't find consensus folder" && \
+      docker logs sia-container && \
+      exit 1)
+  fi
 
-curl -A "Sia-Agent" "http://localhost:9980/consensus"
+  curl -A "Sia-Agent" "http://localhost:9980/consensus"
 
-docker rm -f sia-container
+  docker rm -f sia-container
+  popd
+done
